# Generated by Django 3.2.6 on 2021-08-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_animal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='no image', upload_to='images/'),
            preserve_default=False,
        ),
    ]
